(global-set-key (kbd "C-b") 'backward-kill-word)
(global-set-key (kbd "C-f") 'ag)
(global-set-key (kbd "s-r") 'replace-string)
(global-set-key (kbd "s-<mouse-1>") 'mc/add-cursor-on-click)
(global-set-key (kbd "C-N") 'mc/mark-next-like-this)
(global-set-key (kbd "C--") 'kill-whole-line)
